### ISSUE TITLE
Remove grayed out backdrop from ALT+F2?

### ISSUE THREAD

**Issue by mwoz123** [fujimo-t/gnome-shell-extension-e-ink-mode#1]
First of all many thanks for the extension :) 

As Dasung recommends using as much white color as possible (to expand lifespan), 
is there a possibility to remove the grayed out backdrop (when pressing e.g ALT+F2)  as on the screenshot:
![Screenshot from 2021-02-06 13-12-10](https://user-images.githubusercontent.com/4487025/107117812-1eb04000-687d-11eb-946c-a871419012e2.png)

**Comment by fujimo-t** [comment]
I tried to figure out it but couldn't find out how to change.
I will try again.

**Comment by fujimo-t** [comment]
It seems to be impossible to fix this without modifications of GNOME Shell's source code.
The parameters of backdrop's radial effect is hard corded in [lightbox.js](https://github.com/GNOME/gnome-shell/blob/master/js/ui/lightbox.js) so can't modify from CSS or GSettings.

**Comment by mwoz123** [comment]
Oh I see ..

How about posting issue on gnome shell?
To be able to change the lightbox background color (maybe also for color monitors it will be sometime usefull to have red background when error happens? and for E-ink white/transparent white) 
or have ablity to disable the lightbox as it's will better support E-ink monitors / can expand E-ink lifespan?

**Comment by fujimo-t** [comment]
I don't think GNOME accepts such function just for minority uses so I won't fix this.
