### ISSUE TITLE
Change background to white & restore previous on disable 

### ISSUE THREAD

**Issue by mwoz123** [fujimo-t/gnome-shell-extension-e-ink-mode#2]
How about setting background color to white on enabling plugin ?
And restoring previous on disable ?

**Comment by fujimo-t** [comment]
This plugin doesn't have the function currently.
I want to implement it when I have a time.

**Comment by fujimo-t** [comment]
Implemented in [v3](https://github.com/fujimo-t/gnome-shell-extension-e-ink-mode/releases/tag/3).

**Comment by mwoz123** [comment]
Great many thanks:) Can't wait to download it from gnome-extensions :)
