### ISSUE TITLE
Release for GNOME 41

### ISSUE THREAD

**Issue by bgklc** [fujimo-t/gnome-shell-extension-e-ink-mode#3]
It would be great if you could release that for GNOME 41. Thanks!

**Comment by fujimo-t** [comment]
Thank you to use this extension!
I won't maintain this extension because I have moved to KDE from GNOME.
I will take over this project whoever want to do.

**Comment by bgklc** [comment]
Does KDE have the same functionality for e-ink displays?

**Comment by fujimo-t** [comment]
KDE doesn't have a high contrast theme like GNOME but it can configure color scheme freely without third party extensions or themes.
KDE is high configurable and features of this extension are reproducible with the default setting tool.

But I think GNOME is better than KDE in the aspect of stability, simplicity and UI consistency.

**Comment by fujimo-t** [comment]
I'm currently use KDE and this extension hasn't been maintained. 
But I will separate GNOME theme only to new repository and continue maintenance.

The reasons:
* It looks that there are some users who need to maintenance.
* Most important part of this extension is GNOME Shell theme. Others can be set from GNOME settings tool or Tweaks by users.
* Switch between E-ink and normal mode isn't worked as intended.

**Comment by fujimo-t** [comment]
@bgklc [The theme](https://github.com/fujimo-t/gnome-shell-theme-e-ink) has been released!
Could you try it on GNOME 41?

**Comment by bgklc** [comment]
Gnome panel text disappears with your theme (seems to appear light green on white, almost invisible on LCD, totally invisible on e-ink).

**Comment by bgklc** [comment]
![image](https://user-images.githubusercontent.com/930395/151693923-16e2e1bb-b11e-4583-8fbb-7a30c4b05e47.jpeg)

**Comment by bgklc** [comment]
However after switching different themes like adwaita-dark then adwaita-default and enabling the e-ink user theme after that I encountered normal text on the panel:

![image](https://user-images.githubusercontent.com/930395/151694079-2992d012-da45-44df-8c1f-c2ef0d630c7d.jpeg)

**Comment by fujimo-t** [comment]
I confirmed it on GNOME 41with high contrast gtk theme.
But not happened with other gtk themes like Adwaita.
I will research it.

**Comment by fujimo-t** [comment]
@bgklc I fixed the issue. Could you try again with [v1.0.1](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v1.0.1)?

**Comment by fujimo-t** [comment]
Move to https://github.com/fujimo-t/gnome-shell-theme-e-ink/issues/1
