### ISSUE TITLE
Ubuntu 21.04 Dock has dark background

### ISSUE THREAD

**Issue by Bushstar** [fujimo-t/gnome-shell-extension-e-ink-mode#4]
Just upgraded to Ubuntu 21.04, installed this extension but the Dock background is still dark.

**Comment by fujimo-t** [comment]
Thanks to report!
I plan to [maintenance GNOME Shell theme only](https://github.com/fujimo-t/gnome-shell-extension-e-ink-mode/issues/3#issuecomment-1019159171) and check this issue after release of the theme.

**Comment by Bushstar** [comment]
Apologies, I should have closed the issue. The problem was that I had not set a white background and the semi-transparent Dock appeared to be dark. Once setting white as the background the issue was resolved, I'd forgotten about this from first setting up your excellent extension. Thanks for your work on this, makes my Ubuntu on my Dasung Paperlike a much better experience.

**Comment by fujimo-t** [comment]
Move to https://github.com/fujimo-t/gnome-shell-theme-e-ink/issues/2.
